name: ci

on:
  push:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: npm ci
      - run: npm run build --if-present
      - name: build and push to docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repositoty }}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}
