name: CI

on:
  push:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      #- run: npm test
      - name: build and push to docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repositoty }}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}
		  
		  
		  si hablamos del dataset debemos decir que este contiene 2240 registros, 
		  los cuales se distribuyen en 29 atributos los cuales pueden clasificarse 
		  en las siguientes tablas:
		  
		 informacion del cliente, los productos, las promociones y por ultimo el lugar donde se realiza la compra de x poducto